DROP DATABASE IF EXISTS NNFU;

CREATE DATABASE NNFU;
USE NNFU;

CREATE TABLE Users(
    PW VARCHAR(100),
    EMAIL VARCHAR(100) NOT NULL PRIMARY KEY,
    FLAG INT DEFAULT 0,
    AUTHKEY VARCHAR(100),
    PHOMENUM VARCHAR(20)
);

CREATE TABLE News(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(100) NOT NULL,
    CONTENTS VARCHAR(5000) NOT NULL,
    SCORE INT NULL,
    CAREGORIZE VARCHAR(50) NOT NULL,
    GRNAME VARCHAR(100) NOT NULL,
    FLAG INT DEFAULT 1,
    USER VARCHAR(100)
);

CREATE TABLE Reporter(
    GROUP VARCHAR(100) NOT NULL,
    USER_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    SCORE INT,
    BADCNT INT DEFAULT 0
);

CREATE TABLE Comments(
    NEWS_ID INT NOT NULL,
    USER_ID VARCHAR(100) NOT NULL,
    GOOD INT DEFAULT 0,
    BAD INT DEFAULT 0
);
