DROP DATABASE IF EXISTS NNFU;

CREATE DATABASE NNFU;
USE NNFU;

CREATE TABLE Users(
    PW VARCHAR(100),
    EMAIL VARCHAR(100) NOT NULL PRIMARY KEY,
    FLAG INT DEFAULT 0,
    AUTHKEY VARCHAR(100),
    PHOMENUM VARCHAR(20)
);

CREATE TABLE News(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL,
    CONTENTS VARCHAR(5000) NOT NULL,
    SCORE INT NULL,
    CAREGORIZE VARCHAR(50) NOT NULL,
    GRNAME VARCHAR(100) NOT NULL,
    FLAG INT DEFAULT 1,
    USER VARCHAR(100)
);

CREATE TABLE Reporter(
    USER VARCHAR(100) NOT NULL PRIMARY KEY,
    SCORE INT NULL,
    GRNAME VARCHAR(100) NOT NULL

);

CREATE TABLE Comments(
    NEWS_ID INT NOT NULL,
    USER VARCHAR(100) NOT NULL,
    GOOD INT DEFAULT 0,
    BAD INT DEFAULT 0
);

CREATE TABLE Gr(
    BADCNT INT DEFAULT 0,
    GRNAME VARCHAR(100) NOT NULL PRIMARY KEY,
    BEST INT DEFAULT 0,
    GRURL VARCHAR(100) NOT NULL,
    NOBADTIME INT DEFAULT 0
);
CREATE TABLE MAIL(
    TOUSER VARCHAR(100) NOT NULL,
    FROMUSER VARCHAR(100) NOT NULL,
    CONTENTS VARCHAR(1000) NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);